# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b24b651339847e09de89143e66ff13f502c599f9d89d62d11c9ffb93ecff6b577ae2a8239d00dedcd60edad06348cfaf0cd5d1bde029f52b9ab72247c97e4a73

test:
  secret_key_base: 3bf5d3bedaa84d350112346eace44934fdaf80fbc65c9277e4c001f12b9af575c7145b96f4dfca5d1d0cfdddf86f8e8974ad4f8ae90bae322effb44a88094746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
