# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a24a0bb0045f632328ce59d66712efb017432452511412dfaadd68e7dab73c5099fbdf366eb317afea9435ad8567d2da097ce5f074a94fa50d03bb402f9d4cbb

test:
  secret_key_base: 1fd995df1f8207a8cc73943a3da5fd4cfc6789148abc4fc3e216cd02737783511780e01f3859f58d2e643096fd4a2d86bbdca09b2748b8790afe47b6ba7ea392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
